const featuredFilms = [
  {
    slug: "chidiya",
    title: "Chidiya",
    year: "30 May, 2025",
    category: "Feature Film",
    runtime: "Feature",
    platform: "Amazon Prime",
    watchLink:
      "https://www.primevideo.com/detail/Chidiya/0NSG80VFP6GEU06KL64ER8MUYD",
    poster: "/images/chidiya-1920x1080.webp",
    posterPortrait: "/images/chidiya-1000x1500.webp",
    synopsis:
      "Shanu and Bua, two young brothers living in a cramped chawl in Mumbai, discover badminton while seeking work at a film studio. This discovery sparks a dream that seems far beyond their reach. With their mother's unwavering support and the quirky neighbors rallying behind them, the boys transform a junkyard into their own badminton court. Their journey, marked by trials and imagination, becomes a tribute to youthful determination and the power of dreams.",
    cast: [
      "Svar Kamble as Shanu",
      "Ayush Pathak as Bua",
      "Vinay Pathak as Bali",
      "Amruta Subhash as Vaishnavi",
    ],
    crew: "Mehran Amrohi",
    trailerUrl: "https://www.youtube.com/embed/zsDSJRnoN7w",
    duration: "1h 51min",
  },
  {
    slug: "teen-do-paanch",
    title: "Teen Do Paanch",
    year: "7 May, 2021",
    category: "Web Series",
    runtime: "Series",
    platform: "JioHotstar",
    watchLink: "https://www.hotstar.com/in/shows/teen-do-paanch/1260061897",
    poster: "/images/tdp-1920x1080.webp",
    posterPortrait: "/images/tdp-1000x1500.webp",
    synopsis:
      "Vishal and Priyanka wanted one child. Just one. But life, as it turns out, had a very different plan. What begins as a simple dream of starting a family spirals into the most beautiful, overwhelming, laugh-out-loud chaos two people could ever find themselves in. Adoption, pregnancy, chaos. Teen Do Paanch is the story of a couple who got more love than they ever bargained for, and must now figure out if they have enough in them to hold it all together.",
    cast: [
      "Shreyas Talpade as Vishal",
      "Bidita Bag as Priyanka",
      "Brijendra Kala as Gambhir",
    ],
    crew: "Amitabh Verma",
    trailerUrl: "https://www.youtube.com/embed/d3D-w5LzU9I",
    duration: "13 Episodes",
    episodes: 13,
  },
  {
    slug: "meethi-eid",
    title: "Meethi Eid",
    year: "June 5, 2019",
    category: "Short Film",
    runtime: "Short",
    platform: "ZEE5",
    watchLink: "https://zee5.onelink.me/RlQq/bny5h8wg",
    poster: "/images/meethi-eid-1920x1080.webp",
    posterPortrait: "/images/meethi-eid-1000x1500.webp",
    synopsis:
      "Meethi Eid is a story about what happens when innocence refuses to see the boundaries that adults have spent years building. Rahila and Jyoti don't share the same background, the same status, or the same faith. But on the morning of Eid, none of that matters. A 6-minute ZEE5 Original that will stay with you long after it ends. Starring Paridhi Sharma.",
    cast: ["Paridhi Sharma", "Dishita Sehgal"],
    crew: "Saptaraj Chakraborty, Shiva Varma",
    trailerUrl: "",
    duration: "6min",
  },
  {
    slug: "rishtey-mein-toh-hum-tumhare",
    title: "Rishtey Mein Toh Hum Tumhare",
    year: "16 June, 2019",
    category: "Short Film",
    runtime: "Short",
    platform: "ZEE5",
    poster: "/images/rmtht-1920x1080.webp",
    posterPortrait: "/images/rmtht-1000x1500.webp",
    synopsis:
      "Dad, the engine oil is fine. The paperwork is fine. Everything is fine. Please go to sleep. Every son knows this conversation. And yet, somehow, it never gets old. Rishtey Mein Toh Hum Tumhare is a 7-minute ZEE5 Original about the man who has a question for everything, and the son who has heard it all before. Annoying? Absolutely. But underneath every unnecessary query is a love that neither of them would trade for anything. This Father's Day, celebrate the dad who never stops asking.",
    cast: ["Mahesh Thakur as Khurana Saheb", "Mishkat Varma as Nirmal Khurana"],
    crew: "Saptaraj Chakraborty, Shiva Varma",
    trailerUrl: "",
    watchLink: "https://zee5.onelink.me/RlQq/j2u86sgk",
    duration: "7min",
  },
  {
    slug: "tara-bhaiya-zindabad",
    title: "Tara Bhaiyya Zindabad",
    year: "7 September, 2022",
    category: "Web Series",
    runtime: "Series",
    platform: "Watcho",
    watchLink: "https://www.watcho.com/tvshow/tara-bhaiyya-zindabad-1",
    trailerUrl: "https://youtu.be/h3tHx3Qd0gg?si=q0TVXN38f1ttEQdr",
    poster: "/images/tara-bhaiya-zindabad-1920x1080.webp",
    posterPortrait: "/images/tara-bhaiya-zindabad-1000x1500.webp",
    synopsis:
      "Tara Bhaiyya has ruled his village for years. He knows everyone, controls everything, and answers to nobody. But when a government rule bars anyone with more than two children from contesting elections, his entire political empire is suddenly one technicality away from collapse. What follows is exactly what you would expect from a man like Tara Bhaiyya. Schemes that somehow get worse with every episode. Tara Bhaiyya Zindabad is an 8-episode comedy series about the gloriously ridiculous lengths a small-town politician will go to hold onto power. Set in the heart of Uttar Pradesh, it is loud, chaotic, and completely unmissable.",
    cast: ["Sunil Kumar Verma", "Pratibha Awasthi", "Preeti Shukla"],
    crew: "Mehran Amrohi",
    duration: "8 Episodes",
    episodes: 8,
  },
  {
    slug: "honeymoon-trip",
    title: "Honeymoon Trip",
    year: "6 Feb, 2026",
    category: "Short Film",
    runtime: "Short",
    platform: "Youtube",
    poster: "/images/honeymoon-trip-options-3---1920x1080.webp",
    posterPortrait: "/images/honeymoon-trip-1000x1500.webp",
    synopsis:
      "Aditya and Richa set off on their dream honeymoon, just the two of them and the highway ahead. Then a stop at a lonely dhaba. A strange boy with a disturbing story. And a pair of blood-stained red bangles that have no business being inside their car. Then the radio comes on. And it begins to tell their story. Their secrets. Their past. Their fate. Honeymoon Trip is a thriller that starts as a love story and ends somewhere you never see coming. Every mile darker than the last.",
    cast: ["Mohamad Amir as Aditya", "Ishana Pandey as Richa"],
    crew: "Mehran Amrohi",
    trailerUrl: "https://youtu.be/cZVlEdQ-Jco?si=NYHDucQZq1-DOky5",
    duration: "13min 55sec",
  },
  {
    slug: "papa-ka-scooter",
    title: "Papa Ka Scooter",
    year: "30 October, 2025",
    category: "Web Series",
    runtime: "Series",
    platform: "Watcho",
    watchLink: "https://www.watcho.com/tvshow/papa-ka-scooter",
    poster: "/images/papakascooter-1920x1080.webp",
    posterPortrait: "/images/papakascooter-1000x1500.webp",
    synopsis:
      "28 years old Bunty promises to himself to give a scooter as a birthday gift on his father's birthday. A scooter named Dular chacha was a very precious possession his father Ramakant had during Bunty's teenage days. But due to the paucity of money Ramakant had to sell Dular chacha to pay the fee for Bunty's engineering college.",
    cast: ["Bhoomi Shukla as Rajni", "Rishabh Rai as Bunty Mishra"],
    crew: "Mehran Amrohi",
    trailerUrl: "https://youtu.be/CfdljmmJgfg?si=wHPmcQgUBZByExQh",
    duration: "8 Episodes",
    episodes: 8,
  },
  {
    slug: "happy-anniversary",
    title: "Happy Anniversary",
    year: "",
    category: "Short Film",
    runtime: "Short",
    platform: "",
    poster: "/images/happy-anniversary-1920x1080.webp",
    posterPortrait: "/images/happy-anniversary-1000x1500.webp",
    synopsis:
      "She cooked his favourite meal, wore her best saree and waited by the phone with a smile but when he called to say he wasn't coming, something in her quietly gave way. Her son, like always, reminded her to take her medicine. Happy Anniversary is a story of an old woman who just wanted one evening with the man she loves. What she gets instead is a dream of him, a scattered pile of medicines and a silence that says everything nobody in her family bothered to.",
    cast: ["Mani Verma", "Arunendra Nath Verma"],
    crew: "Nishant Chaturvedi",
    trailerUrl: "",
    duration: "",
  },
  {
    slug: "private",
    title: "Private",
    year: "",
    category: "Short Film",
    runtime: "Short",
    platform: "",
    poster: "/images/private-1920x1080.webp",
    posterPortrait: "/images/private-1000x1500.webp",
    synopsis:
      "All she ever wanted was to wear a gown. Just once. Every day she washed them, ironed them, and hung them back carefully while her employer lived the life she quietly dreamed of. Private is a story about desire, loyalty, and the cruel joke life plays on those who ask for the least. Did she finally get her gown or did she lose everything?",
    cast: ["Meena Wardhan", "Shahid Hussain (Bobby)"],
    crew: "Nishant Chaturvedi",
    trailerUrl: "",
    duration: "",
  },
  {
    slug: "macho-sporto-presents-sk-fanzone",
    title: "Macho Sporto Presents SK Fanzone",
    year: "13 May, 2023",
    category: "Commercial",
    runtime: "Short",
    platform: "Youtube",
    poster: "/images/macho-sporto-presents-sk-fanzone-1920x1080.webp",
    posterPortrait: "/images/macho-sporto-presents-sk-fanzone-portrait.webp",
    synopsis:
      'Macho Squad\'s "My Toing" is an engaging online contest where fans vote for the most charming and stylish men. The competition celebrates confidence, personality, and modern masculinity, bringing together audiences who appreciate style, charisma, and individuality.',
    cast: [],
    crew: "",
    trailerUrl: "https://youtu.be/LRToqJXj-Ck?si=HrtFGm-9WY3tr3f8",
    duration: "5mins",
  },
  {
    slug: "macho-sporto-presents-sk-squad",
    title: "Macho Sporto Presents SK Squad",
    year: "13 May, 2023",
    category: "Commercial",
    runtime: "Short",
    platform: "Youtube",
    poster: "/images/macho-sporto-presents-sk-squad.webp",
    posterPortrait: "/images/macho-sporto-presents-sk-squad-portrait.webp",
    synopsis:
      'Macho Squad\'s "StreetVaani" is a series of candid street interviews where everyday people share their honest and unfiltered perspectives on life, style, and culture. Capturing authentic voices from the streets, the series celebrates bold opinions, diverse viewpoints, and real conversations.',
    cast: [],
    crew: "",
    trailerUrl: "https://youtu.be/EWPYNm2D59k?si=ZQEvKp3q5sfrv2hI",
    duration: "5mins",
  },
  {
    slug: "nitu-ghanghas",
    title: "NITU GHANGHAS",
    year: "1 Oct 2023",
    category: "Commercial",
    runtime: "Short",
    platform: "Youtube",
    poster: "/images/nitu-ghanghas.webp",
    posterPortrait: "/images/NITU-GHANGHAS-1000X1500.webp",
    synopsis:
      "This episode is part of HDFC Life's Behind The Journey – Season 4, featuring Indian boxer Nitu Ghanghas, who reflects on her inspiring journey from humble beginnings to becoming a champion. Through a candid conversation, she shares the challenges, sacrifices, and determination that shaped her career, offering viewers a glimpse into the resilience and mindset required to pursue dreams at the highest level of sport.",
    cast: [],
    crew: "",
    trailerUrl: "https://youtu.be/etLkolOxER0?si=bXOx_JXrld58ZDrR",
    duration: "4mins",
  },
  {
    slug: "hum-hai-india",
    title: "Hum Hai India",
    year: "15 Aug 2019",
    category: "Music Video",
    runtime: "Short",
    platform: "Youtube",
    poster: "/images/Hum-hai-Indian-1920x1080.webp",
    posterPortrait: "/images/Hum-Hai-India-1000x1500.webp",
    synopsis:
      "Hum Hain India is a powerful anthem celebrating the spirit, diversity, and unity of the nation. Featuring Arjun Rampal, Tanuj Virwani, Kanika Mann, Nishant Malkani, Dia Mirza, Aahana Kumra, Jimmy Shergill, Sharad Kelkar, and Gul Panag, the music video highlights stories of resilience, ambition, and pride that reflect the collective strength of India.",
    cast: [
      "Arjun Rampal",
      "Tanuj Virwani",
      "Kanika Mann",
      "Dia Mirza",
      "Aahana Kumra",
      "Jimmy Shergill",
      "Sharad Kelkar",
    ],
    crew: "Nishant Chaturvedi | Producers: Faqhrul Husaini & Mehran Amrohi",
    trailerUrl: "https://youtu.be/KZxvEg38iVI?si=azhMDxSpkhQT2ju3",
    duration: "4min",
  },
];

export type Film = (typeof featuredFilms)[number];
export { featuredFilms };
